// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantOrderManager.Api.Data;

#nullable disable

namespace RestaurantOrderManager.Api.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20251016170707_SeedSecondaryData")]
    partial class SeedSecondaryData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantOrderManager.Shared.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("RestaurantOrderManager.Shared.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Classic pizza with tomato sauce, mozzarella, and basil.",
                            Name = "Margherita Pizza",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Crisp romaine lettuce with Caesar dressing, croutons, and Parmesan cheese.",
                            Name = "Caesar Salad",
                            Price = 6.49m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pasta with eggs, cheese, pancetta, and pepper.",
                            Name = "Spaghetti Carbonara",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Grilled chicken breast with lettuce, tomato, and mayo on a toasted bun.",
                            Name = "Grilled Chicken Sandwich",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Warm chocolate cake with a gooey chocolate center.",
                            Name = "Chocolate Lava Cake",
                            Price = 5.49m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Piciburgir",
                            Name = "Sajtburger",
                            Price = 1.0m
                        });
                });

            modelBuilder.Entity("RestaurantOrderManager.Shared.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantOrderManager.Shared.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderNumber = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            OrderNumber = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            OrderNumber = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            OrderNumber = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            OrderNumber = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            OrderNumber = 0,
                            Status = 0
                        });
                });

            modelBuilder.Entity("RestaurantOrderManager.Shared.Models.CartItem", b =>
                {
                    b.HasOne("RestaurantOrderManager.Shared.Models.Order", null)
                        .WithMany("CartItems")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("RestaurantOrderManager.Shared.Models.Order", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
