// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantOrderManager.Api.Data;

#nullable disable

namespace RestaurantOrderManager.Api.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20251016173036_SeedOrdersData")]
    partial class SeedOrdersData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantOrderManager.Shared.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("CartItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuItemId = 1,
                            Name = "Margherita Pizza",
                            OrderId = 1,
                            Price = 8.99m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            MenuItemId = 2,
                            Name = "Caesar Salad",
                            OrderId = 1,
                            Price = 6.49m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            MenuItemId = 3,
                            Name = "Spaghetti Carbonara",
                            OrderId = 2,
                            Price = 10.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            MenuItemId = 4,
                            Name = "Grilled Chicken Sandwich",
                            OrderId = 2,
                            Price = 7.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            MenuItemId = 5,
                            Name = "Chocolate Lava Cake",
                            OrderId = 2,
                            Price = 5.49m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 6,
                            MenuItemId = 1,
                            Name = "Margherita Pizza",
                            OrderId = 3,
                            Price = 8.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            MenuItemId = 3,
                            Name = "Spaghetti Carbonara",
                            OrderId = 3,
                            Price = 10.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 8,
                            MenuItemId = 2,
                            Name = "Caesar Salad",
                            OrderId = 4,
                            Price = 6.49m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 9,
                            MenuItemId = 4,
                            Name = "Grilled Chicken Sandwich",
                            OrderId = 4,
                            Price = 7.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            MenuItemId = 6,
                            Name = "Fruit Juice",
                            OrderId = 4,
                            Price = 1.50m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 11,
                            MenuItemId = 5,
                            Name = "Chocolate Lava Cake",
                            OrderId = 5,
                            Price = 5.49m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 12,
                            MenuItemId = 7,
                            Name = "Espresso",
                            OrderId = 5,
                            Price = 2.99m,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("RestaurantOrderManager.Shared.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Classic pizza with tomato sauce, mozzarella, and basil.",
                            Name = "Margherita Pizza",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Crisp romaine lettuce with Caesar dressing, croutons, and Parmesan cheese.",
                            Name = "Caesar Salad",
                            Price = 6.49m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pasta with eggs, cheese, pancetta, and pepper.",
                            Name = "Spaghetti Carbonara",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Grilled chicken breast with lettuce, tomato, and mayo on a toasted bun.",
                            Name = "Grilled Chicken Sandwich",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Warm chocolate cake with a gooey chocolate center.",
                            Name = "Chocolate Lava Cake",
                            Price = 5.49m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Piciburgir",
                            Name = "Sajtburger",
                            Price = 1.0m
                        });
                });

            modelBuilder.Entity("RestaurantOrderManager.Shared.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 16, 19, 0, 35, 736, DateTimeKind.Local).AddTicks(3415),
                            State = 2,
                            TableId = 1,
                            Total = 24.47m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 16, 19, 15, 35, 736, DateTimeKind.Local).AddTicks(3643),
                            State = 1,
                            TableId = 4,
                            Total = 29.96m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 16, 19, 25, 35, 736, DateTimeKind.Local).AddTicks(3648),
                            State = 0,
                            TableId = 6,
                            Total = 19.98m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 16, 19, 20, 35, 736, DateTimeKind.Local).AddTicks(3652),
                            State = 1,
                            TableId = 2,
                            Total = 22.97m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 16, 18, 45, 35, 736, DateTimeKind.Local).AddTicks(3655),
                            State = 2,
                            TableId = 5,
                            Total = 14.48m
                        });
                });

            modelBuilder.Entity("RestaurantOrderManager.Shared.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderNumber = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            OrderNumber = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            OrderNumber = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            OrderNumber = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            OrderNumber = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            OrderNumber = 0,
                            Status = 0
                        });
                });

            modelBuilder.Entity("RestaurantOrderManager.Shared.Models.CartItem", b =>
                {
                    b.HasOne("RestaurantOrderManager.Shared.Models.Order", "Order")
                        .WithMany("CartItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantOrderManager.Shared.Models.Order", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
